#######################################################
#                                                     
#  THE RECIPE
#  by Cesar Marin
#  CERN PH
#  Created on 10/01/2012
#                                                     
#######################################################
# set the DESIGN NAME for the config files. This will also be used for the .lib, .lef, .v, and .spef files
# that are generated by this script
######################################################
set DESIGN {MONOPIX} ;
set DESIGN_FILE $DESIGN;
set PL_EFFORT high ;
set OPT "_soc"
set HOR 1
set CUSTOM 0
#######################################################
# Seting up the Routing Layes TOP & BOTTOM
#######################################################

set preferredTopRoutingLayer [expr $METAL_TOP]
set topRoutingLayer [expr $METAL_TOP]
set clockTopRoutingLayer $METAL_TOP
set clockBottomRoutingLayer [expr $METAL_TOP -2]
set bottomRoutingLayer 1


######################################################
# CORE SIZE
######################################################
# choose numbers that make sense for you
set usepct 0.95 ;# percent utilization in placing cells
set rowgap 0   ;# gap between pairs of std cell rows

set GATEHIGHT 5.6;

set aspect 0.95 ;# aspect ratio of overall cell (1.0 is square)
# less than 1.0 is landscape, greater than 1.0 is portrait

#############################################################
# Standard CELLs Delays - Buffers & Inverters
#############################################################

set CTS_BUFFER { bufbd1 bufbd2  bufbd3 bufbd7 bufbda bufbdf buffd1 buffd3 buffd2  buffda bufbdf bufbdk} ; # Footprint of buffer in .lib file
set CTS_INV { invbd2 invbd4 invbd7 invbda invbdf invbdk } ;# Footprint of inverter in .lib file
set CTS_DELAY { dl01d1 dl01d2 dl01d4 dl02d1 dl03d1 dl02d2 dl02d4 dl04d1 dl03d2 dl03d4 dl04d2 dl04d4 } ;# Footprint of inverter in .lib file


######################################################
# Project values
######################################################



set std_h 5.6

set pad_h 120
set pad_w 100

set numCpu 10
